version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: Alej33
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: fastapi
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fullstack-data-network

  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: kong
    networks:
      - fullstack-data-network

  kong-migration:
    image: kong:latest
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: 123456789
      KONG_PG_DATABASE: kong
    networks:
      - fullstack-data-network

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: 123456789
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
    depends_on:
      - kong-database
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    restart: on-failure
    networks:
      - fullstack-data-network

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: fastapi
      DB_USER: Alej33
      DB_PASSWORD: 123456789
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack-data-network

networks:
  fullstack-data-network:
    driver: bridge
