version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: Alej33
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: fastapi
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fullstack-data-network

networks:
  fullstack-data-network:
    driver: bridge
